import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Sidebar from "./_components/Sidebar";

const muslihFont = localFont({
  src: "./_fonts/mulish/Mulish-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${muslihFont.className} w-full flex flex-row`}>
        <Sidebar className="bg-[#363740] w-full max-w-[255px] h-screen hidden lg:flex flex-col gap-6" />
        {children}
      </body>
    </html>
  );
}
